title: Web9.0
description: " C@ and  Arrow#  and  All C type  Sections  is  called as new  name  WEB 9.0.  C    has  no latest   child.   SO  C@    is       formed  with    the  combination  of   C  and  WEB   so  we  called   as  C@  P.L.  It  is  invented   at  year    2013  by  wilmix  jemin  j.  But   Arrow#  is  invented   at  year  2014."
google_analytics: 
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
